os: windows
language: shell
# before_install:
#   - CARGO_INCREMENTAL=1
#   - RUSTFLAGS="-Z thinlto -C codegen-units=16"
script:
 - docker version
 - docker build -t windows .
 - docker push holochain/travis-windows-proto:windows
