os: windows
language: shell
# hurrrrrrrrrr
# https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
filter_secrets: false
# script:
# - docker build -t windows .
# # https://stackoverflow.com/questions/51489359/docker-using-password-via-the-cli-is-insecure-use-password-stdin
#
# - docker tag windows:latest holochain/travis-windows-proto:latest
# - docker push holochain/travis-windows-proto:latest
env:
  global:
  - secure: hkgmWzQTIenJghfTf/3ILiiDEk8GRa8fq8eJKIkjYSQjhrBrhRoH74m7EU+8aihRIodQYR4etoJSaR0qqRQ4UOGXT2xWXEWq84MJFcjx6ci2ILFaEvYPDWXY6BnQA69KBCEqkPjZRuIq/MeBRdY7zIYEq9kkH9dgnKGz1IXxOfn+zVtPcrc4V1jUOmdzoApDhW4fFINrifIz1fWPZ50rwiTL94BwJ0a0riRQF55AY3ZolTlylr9UwoApku4mUtYk7eqWMipuHKFXHSY/nuArRrHQzJQmfxkbCYp4ogwAclWT/TgewZcVmlToNv+ygcyG40VAXrWXiuYE0uxA1FciXayzTz6HuubpD1VT0ewoLB+Oipvy+pWSv27y6lAZjXSQSol6XIzE2OaI7KFZOJJ4MJqFZKiHAZasfNBLFrekgp4m0MbF3ziciOki284ZgPrL8kAVHl2YKTF5kFFSKagfrlHmK13P/vMBUWQIljG32sFQy9Oz9OOX6m/34j57FqLz2JlR0eJzBePqZOEKhlsku2XEBl8HGiC3fAydj4DUipM9kIbmb/s+CzjWbxVC0b5E+hWFNTCt/csLV3ZpUFcNjpDywXliCS6JZSVZlBX26rCK+kVQNjHLlK5o5ea7ahM81BK57KWL9AkeKhGLXh9VlCBdRT4O1UWwmFzhEFqYGvE=
  - secure: CNgUUxOv6pDQ82NMWtYA9kP7kAxfoc56320fnnvibpnfawpxGAAuU69dHyQK0xtfVM88qaXpwD9qudLKaP8MCzowqNllgwfbvzh7X716XObXeN++qYRCpy+NeazDJWhteOaIKiAL9kN41AHmD4IZMIKqB1wicxUB5f0/PM2v2VPqWMGgOQoPAgNGzhKDT8UGoLZyAS8k4Pmb436wojICzKR+uL0NS2JV+zNcZKarHf9OWRlB0i6QwpGzDDjlaf+QE2DiahDV524z3O07bQR2UlNQs/9psfgxSpv8gALer1wwcODh2SXWgXe0LZbaxZZHMYNh/1yCvy7AEy4LNGhlyik6AX7wJ861IlyNAsd4tvwWSiM5ZA9afwo4gvF4mjIayhRcxAHvecX5+MLp2c3Pt9/R/662Y3hj6i0nZsESI+iixkpFVXJggVxTBA92MFqjaw8fbj/YaeAREwF4dSLQKCD+HU5EHJ6H2lb30Zhwe3gypgxxIwcSz6CCkdS2sv9CMpWGfBfjz+sImPXI2eilT7PjhMStsGIXLtkOx8VwBTrl1xMA73mrWtZrLxrLgHDZamCge+VEjoY6grD3A2Wf8G6xHmX7lvYooat2WtV61gPps1ncaF0Xg50CUpOiX3eZ5lm1y8bmHVubJrBB+JkPpgvhk7t2duPxW3gjsJn7PaQ=

jobs:
 include:
   - stage: docker.start
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull microsoft/windowsservercore:1803
       - docker build --cache-from microsoft/windowsservercore:1803 -f Dockerfile..start -t holochain/travis-windows-proto:windows..start .
       - docker push holochain/travis-windows-proto:windows..start

   - stage: docker.01
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull holochain/travis-windows-proto:windows..start
       - docker build --cache-from holochain/travis-windows-proto:windows..start -f Dockerfile.01.build-tools -t holochain/travis-windows-proto:windows.01.build-tools .
       - docker push holochain/travis-windows-proto:windows.01.build-tools

   - stage: docker.02
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull holochain/travis-windows-proto:windows.01.build-tools
       - docker build --cache-from holochain/travis-windows-proto:windows.01.build-tools -f Dockerfile.02.rust -t holochain/travis-windows-proto:windows.02.rust .
       - docker push holochain/travis-windows-proto:windows.02.rust

   - stage: docker.03
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull holochain/travis-windows-proto:windows.02.rust
       - docker build --cache-from holochain/travis-windows-proto:windows.02.rust -f Dockerfile.03.choco -t holochain/travis-windows-proto:windows.03.choco .
       - docker push holochain/travis-windows-proto:windows.03.choco

   - stage: docker.04
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull holochain/travis-windows-proto:windows.03.choco
       - docker build --cache-from holochain/travis-windows-proto:windows.03.choco -f Dockerfile.04.nodist -t holochain/travis-windows-proto:windows.04.nodist .
       - docker push holochain/travis-windows-proto:windows.04.nodist

   - stage: docker.end
     - script:
       - echo "$DOCKER_PASSWORD" | docker login docker.io -u $DOCKER_USER --password-stdin
       - docker pull holochain/travis-windows-proto:windows.04.nodist
       - docker build  --cache-from holochain/travis-windows-proto:windows.04.nodist -f Dockerfile.zz.end -t holochain/travis-windows-proto:windows.zz.end -t holochain/travis-windows-proto:latest .
       - docker push holochain/travis-windows-proto:windows.zz.end
       - docker push holochain/travis-windows-proto:latest
