# escape=`

FROM holochain/travis-windows-proto:windows.02.rust

RUN @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" `
    -NoProfile `
    -InputFormat None `
    -ExecutionPolicy Bypass `
    -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

ENV PATH "${PATH};${ALLUSERSPROFILE}\chocolatey\bin"
RUN echo %PATH%
RUN choco --version
