# escape=`

FROM holochain/travis-windows-proto:windows.02.rust

RUN powershell `
    -NoProfile `
    -InputFormat None `
    -ExecutionPolicy Bypass `
    -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

RUN setx path '%path%;%ALLUSERSPROFILE%\chocolatey\bin'

RUN choco --version
