# escape=`

FROM holochain/travis-windows-proto:windows.03.choco

RUN choco install -y git.install nodist

RUN choco install nodist

RUN echo %NODE_PATH%

RUN setx path '"%path%;C:\Program Files (x86)\Nodist\bin"'
RUN echo %path%

RUN nodist add 8
RUN nodist 8

RUN node --version
RUN npm --version
